[tool.poetry]
name = "starrailcard"
version = "1.2.6"
description = "Module for generating Honkai Star Rail character cards"
authors = ["None"]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/DEViantUA/StarRailCard"
homepage = "https://github.com/DEViantUA/StarRailCard"

keywords = ["honkai", "cards", "generation", "honkaistarraill","raill", "starraill", "builds", "honkairail", "honkai"] 

[tool.poetry.dependencies]
Pillow = "^10.0.1"
honkairail = "^1.1.4"
python = "^3.9"
beautifulsoup4 = "^4.12.3"
aiohttp = "^3.9.3"

[tool.poetry.dev-dependencies]
cachetools = "^5.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
